name: fire!

on:
  schedule:
    - cron: '20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: execute
        env:
          TZ: UTC
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sh ./run.sh
